### ISSUE TITLE
Provide a command to export bash file with all salt in it

### ISSUE THREAD

**Issue by verhulstm** [terminal-labs/rambo#143]

**Comment by nixjdm** [comment]
Are you thinking more of sneaking Salt in / masquerading it as Bash, or of converting the Salt into Bash that serves the same purpose but does not have any embedded Salt?

**Comment by verhulstm** [comment]
sneaking Salt in.

with a base 64 encoded payload and extracting this to a tmp dir, running salt state, and deleting all tmp stuff post run.

I have already started working on this. the emitted bash files will be about 250mb is size.

**Comment by nixjdm** [comment]
I'm feeling like this might be better as a separate tool. You're designing I think something that will take Salt states/grains/pillars/etc and export that plus Salt itself into a runable bash script, so that Salt doesn't literally need to be installed to function. This has some niche uses, but I'm struggling to think of a use in Rambo specifically. Mainly, because with Rambo we have full control of a machine, so it isn't an issue that we install whatever. This tool doesn't really have much to do with controlling VMs from the outside, right?

**Comment by nixjdm** [comment]
Post discussion: I'm closing this ticket in favor of making this a separate project. It is outside of the scope of Rambo and has uses that are entirely separate from Rambo.
