### ISSUE TITLE
names are often too long

### ISSUE THREAD

**Issue by verhulstm** [terminal-labs/rambo#299]
lxc container names cannot be more than 64 chars. 

we need smaller uuids and we need to check the name before we try to build the box.

if the derived name is too long force the user enter a custom name?

**Comment by nixjdm** [comment]
I got lucky with some googling. The cause of whatever error you saw about 64 chars is not because of LXC, but probably because hostnames on most *nix systems are limited to 64 chars. The maintainers of LXC have more than once denied such a limit, but pointed to limits in utsname. See https://stackoverflow.com/questions/8724954/what-is-the-maximum-number-of-characters-for-a-host-name-in-unix

So, this is a more general problem, and probably effects all providers to some degree. I can rework how we calculate the default hostnames later. For one thing, verbose replacements like VAGRANTSLASH or RAMBOSLASH are probably not the best way to do things.

Ref #211
