### ISSUE TITLE
Refactor options.size_option

### ISSUE THREAD

**Issue by smitty42** [terminal-labs/rambo#313]
options.size_option currently handles ram and disk configuration in one monolithic function. Intuitively, these ram / disk should be handled separately, but they are not for reasons of architectural wonkyness / provider requirements. To me, this is indicative of room for improvement in clarity, so at some point we need to take a look at this, see how we can split things out and do a better job of shedding light on the special cases we trying to handle here.

**Comment by nixjdm** [comment]
Specifically as I see it, the core reason for that def's complexity is the design choice to allow either one of ram_size and drive_size to be specified, and then we chose the other from the pairing in the whitelist. 

This design choice was made to attempt to conform hardware specs when switching providers, specifically because DO has them tied together. If DO hadn't done that, we could still just chose single reasonable defaults like the other options. This deserves to be reconsidered, if for no other reason, because [DO is changing their API and available machine types](https://developers.digitalocean.com/documentation/changelog/api-v2/new-size-slugs-for-droplet-plan-changes/). They are even dropping their old machine-types as of July 1, 2018.

When none or both of these options are specified, things are simple, and they can be treated independently just as the other options are handled.

**Comment by verhulstm** [comment]
aws lightsail still uses this std. 

https://aws.amazon.com/lightsail/pricing/

**Comment by verhulstm** [comment]
what about allowing a user to set ram/disc independently and adding a "small, medium, large" option that pairs them?
