### ISSUE TITLE
Multiuser support on Digital Ocean.

### ISSUE THREAD

**Issue by nixjdm** [terminal-labs/rambo#70]
On Digital Ocean, I'd like the ability for multiple people to spin up VMs on an organization's account without interfering so much with each other. Currently it is only really feasible for one person to do this at a time, or to share ssh keys.

**Comment by verhulstm** [comment]
in order to do this you need to set a new API key on DO and store it's value in digitalocean.env.sh. I don't think it matters what you name the api key.

and you need to create a new uniquely named ssh key and upload it's public key to DO. this key file name, DO ssh key name, and entry in export DIGITALOCEAN_PRIVATE_KEY_PATH="auth/keys/[ unique name].pem" in  digitalocean.env.sh must match.

then source digitalocean.env.sh

**Comment by verhulstm** [comment]
This is done right? can we close this ticket?

**Comment by nixjdm** [comment]
Yes.
