### ISSUE TITLE
Cleanup virtualbox vagrantfile box switching

### ISSUE THREAD

**Issue by nixjdm** [terminal-labs/rambo#89]
https://github.com/terminal-labs/rambo/blob/master/rambo/vagrant_resources/vagrant/Vagrantfile.virtualbox#L35-L106 is big and will only get bigger if we don't clean it up.

If we have a little better and more consistent naming conventions, between rambo and https://github.com/terminal-labs/vagrant-boxes we can just have some simple string parsing with the `VM_HOST` var. Either that or some translation layer between the two.

**Comment by alan-cugler** [comment]
I suggest replacing "debian-jessie" with "debian-8" and the that will be consistent to allow parsing together the correct file extension without if statements.

As of now we have each hardrive size being correlated with a RAM size, but this will probably not continue indefinitely. So the if statement for VM_SIZE is reduced to one set that will be manageable for a while, otherwise a key,value pair system can be devised.

**Comment by nixjdm** [comment]
You can rename `debian-jesse` to `debian-8`. Keep the VM_SIZES using RAM for now.

**Comment by nixjdm** [comment]
Handling the case of missing support for something will likely come along with #150, and that may be quite a bit more complex, and is definitely out of scope for this ticket. :)
